name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false  # 让一个平台失败不影响其他平台
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Disable pnpm
        run: |
          echo "Disabling pnpm detection"
          rm -f pnpm-lock.yaml
          rm -f pnpm-workspace.yaml
          npm config set package-manager npm

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Electron app
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_ENV: production
          npm_config_user_agent: npm

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: npx semantic-release